openapi: 3.0.3
info:
  title: Mafia Host API
  description: Mafia Host API
  version: 1.0.0

servers:
  - url: http://localhost:8080/
    description: Locally launched server

paths:
  /games:
    post:
      tags:
        - Game
      summary: Create a new game
      operationId: createGame
      responses:
        '201':
          description: The created game object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: Created game's ID
                required:
                  - id
  /games/{id}:
    get:
      tags:
        - Game
      summary: Get a game by ID
      operationId: getGame
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: The game object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponse'
components:
  schemas:
    GameResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        state:
          type: string
          example: assigning_roles
        gameConfig:
          type: object
          properties:
            roles:
              type: array
              items:
                $ref: '#/components/schemas/RoleDescription'
          required:
            - roles
      required:
        - id
        - state
        - gameConfig
    RoleDescription:
      type: object
      properties:
        name:
          type: string
        team:
          type: string
        count:
          type: integer
      required:
        - name
        - team
        - count